import Head from "next/head";
import Link from "next/link";
import { Button } from '@nextui-org/react'

export default function Home() {
    const digitalSolutions = [
        {
            title: "Intelligent analysis",
            img: "/images/index/card1.png",
            url: "/intelligent-analysis"
        },
        {
            title: "User Experience",
            img: "/images/index/card2.png",
            url: "/user-experience"
        },
        {
            title: "Safety protection",
            img: "/images/index/card3.png",
            url: "/safety-protection"
        },
        {
            title: "Efficient cooperation",
            img: "/images/index/card1.png",
            url: "/efficient-cooperation"
        },
        {
            title: "Global deployment",
            img: "/images/index/card2.png",
            url: "/global-deployment"
        },
        {
            title: "Continuous improvement",
            img: "/images/index/card3.png",
            url: "/continuous-improvement"
        },
        {
            title: "Flexible expansion",
            img: "/images/index/card1.png",
            url: "/flexible-expansion"
        },
        {
            title: "Technical support",
            img: "/images/index/card2.png",
            url: "/technical-support"
        },
        {
            title: "Customizable",
            img: "/images/index/card3.png",
            url: "/customizable"
        },
    ]


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#1D2129] text-white">
        {/*  section1 landing */}
          <div
              className="font-bold text-[48px] text-white h-[calc(100vh-88px)] flex flex-col items-start justify-center px-12 relative">
              <div className={""}>
                  Spreading the Gospel,
              </div>
              <div>
                  One Byte at a Time
              </div>
              <div className={"text-base text-[#9CADCE] mt-4 "}>
                  Empowering Churches Worldwide with Innovative Technology Solutions to Spread God&#39;s Word
              </div>
              <img src="/images/index/bg.png" alt="background" className={"absolute bottom-1/2 transform translate-y-1/2"}/>
              <img src="/images/index/phone-3.png" alt="phones" className={"absolute right-12 bottom-1/2 transform translate-y-1/2"}/>
          </div>

          {/*  section2  fag tech info */}
          <div className={"flex px-12 items-center"}>
              <img src="/images/index/desktop.png" alt="desktop" className={"w-1/2"}/>
              <div className={"text-white pl-4"}>
                  <div className={"text-[48px] "}>FGA Technology</div>
                  <div className={"my-8"}>
                      We are committed to providing comprehensive digital solutions for the church, including software development, website design, network security and other services. Through innovative technology and professional team, we help the church realize digital transformation and improve its ability to preach the gospel.
                  </div>
                  <button className={"rounded-full bg-[#1A2F8A] px-4 py-2"}>
                      Learn more
                  </button>
              </div>
          </div>

          {/*  section3 Digital solutions */}
          <div className={"flex flex-col items-center my-32"}>
              <div  className={"text-[48px]"}>Digital solutions</div>
              <div className={"mt-2 mb-8"}>We provide a variety of efficient digital solutions to help you improve business efficiency and user experience.</div>
              <div className={"grid grid-cols-3 gap-8 w-full px-12"}>
                  {
                        digitalSolutions.map((solution) => {
                            return <div key={solution.title} className={"flex flex-col items-center"}>
                                <img src={solution.img} alt={solution.title} className={"cursor-pointer object-cover"}/>
                                <div className={"text-[24px] mt-4 mb-4"}>{solution.title}</div>
                            </div>
                        })
                  }
              </div>
          </div>


          {/*  section4  learn more*/}
          <div className={"flex flex-col items-center my-32"}>
              <div className={"text-[48px]"}>Learn more about us</div>
              <div className={"mt-2 mb-8"}>Be part of our tech community. Sign up for our newsletter and stay abreast of the latest industry trends.</div>
              <div>
                  <input type="email" className={"rounded-full bg-[#2F323A] px-4 py-2 w-[300px]"} placeholder={"Enter your email address"}/>
                  <button  className={"rounded-full bg-[#1A2F8A] px-4 py-2 ml-6"}>Subscribe</button>
              </div>

          </div>

      </main>
    </>
  );
}
